language: go
sudo: true
go:
  - 1.14.x
services: [docker]
os:
  - linux

deploy:
  provider: releases
  api_key:
    secure: qqO3w/v5vcYPUwN7Gk7yqhrXzjTIWKQ/t57UTCVO+gsIFjeJicjU1Vs2VT3nSAcZpxN/JfLeCbHzJAHwtJpvvHo/7ixesOmJSbv5+e7gGkVGpdIM5iCxbVVmzEcrNk/z41lM2cjhxMqZL7aFt1qL+9Zd/qYHE5bBWR0lRdyTf4Zz+KEj1DShx5B1eHv21xGHtd3tkk5MYNNCic2uTZ2NPsDxtrHp/er3OHzvqyqA03oFhkoPoG2+BsQr/HoFqZyydhUzWjXaVRWD+2Q/2Ao4VBtymuE6WwXj8LDbMZtl4Qs/g+jMHQODfPW78P+fbDbtOaOPYDVR2m10DNLqObX5C/pITVEPlyBBjrhe0iRpSYTo0Ik0io8FdGUsh0vVRHTwbn2e4GAZ2cg/BxsXYsh6UHtQJ0khjV3ZFOsgthTcVLBnEIH0SUKDa3Oku6tEQEqqhnpeutTLlv28Y7upXFdoa9pZ5suS4Uq+r6EWYAAS3tkSx5R0UCyTox+be0g2XK9/k3ZbkIMYg+wDF+A70mzCrZsji+VDDXWsY/dF6GrSWVekn9V/bXNWPi8Yt0aVqdikHluQEeEf63u6KTHV6aOLUT6kidbCi+ogqroe9UXj9gRVRK/73ChZyV+Q65bnSE6iCvhiHEkxEQP8wmVLsIiGx6+X0Fm5SyPEQ6tyBsGQk3c=
  file_glob: true
  file:
    - bin/apitest-*
    - openapi.yaml
  on:
    repo: moov-io/api
    tags: true
    go: 1.13.x
  skip_cleanup: true

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push

notifications:
  slack:
    secure: PSTsskD0WO58YXJLR8c3r1Ow2uDQ9LxCeDpwypdXPk/El3hZ/dg34gpWlclsKacUc+Qw9iAhBwWcoLV3MtPNT10gIu3Zam4u8y0zVSL/q32KD7jcQjoYG+7c6H6MpyoN2bD5mVCpyvT164ne4TLE1E9r3rsMfLiCWcRFM8PQTdIAFyBRZU1muSrk5VLPBTeXfQWo8Cy/Iko+5lEvXjnSJtxly2sXETmR9J7iGge7sxnh7pozLFk16lNC9d/ZAMWguDY9/tJ3mbag6LJIoJ44ThDx/pKihLE35m49SBVsk0C5PDcpHvLyLtb7fs2GsL6s4Km+eFCwO+nYMiUvhkIBIZPeagdkBgohHZYOaKcQ1jWUTYU1/xNem+Rr2RzfKLgMTmD8rV0O2L7rp7x6dVwiom+JgCKQfEqAK0G82ZXplixuFPeah4BW0TGCgfU8QdoQCiBurAbhJ7TLE+wBeiwRoKarc9AWG80KLmdQjE3t2WRT14PgqwTmgjaMeyDT45L5TkWJj50mKNFiDEYUl/NjOOgBDlL4dqaUZ5Oymj82cGQW6TIKzW8q+juHH1r3QRecWZNWYPVgyTjxdS6F5OD4FrwSsud6PLGpeh49W3cIkhiT4HsxIoVmgK5uuxEZoabnhhz3neV6FfqVAZ0nUshCkoVD/SXHlWGl1aYxAqtnlsY=
