language: go
sudo: true
go:
  - 1.13.x
services:
  - docker
os:
  - linux
  - osx
osx_image: xcode9.1
before_install:
  # Setup directory for binaries
  - mkdir ./bin
  - export PATH=$PATH:$PWD/bin
  # Misspell
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_linux_64bit.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O misspell.tar.gz https://github.com/client9/misspell/releases/download/v0.3.4/misspell_0.3.4_mac_64bit.tar.gz; fi
  - tar xf misspell.tar.gz && cp ./misspell ./bin/misspell
  # staticcheck
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O staticcheck.tar.gz https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_linux_amd64.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O staticcheck.tar.gz https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_darwin_amd64.tar.gz; fi
  - tar xf staticcheck.tar.gz && cp ./staticcheck/staticcheck ./bin/staticcheck
  # nancy (vulnerable dependencies)
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L -o ./bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.43/nancy-linux.amd64-v0.0.43; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl -L -o ./bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v0.0.43/nancy-darwin.amd64-v0.0.43; fi
  - chmod +x ./bin/nancy
  # golangci-lint
  - wget -O - -q https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s v1.23.6
  # gocyclo
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ./bin/gocyclo https://github.com/adamdecaf/gocyclo/releases/download/2019-08-09/gocyclo-linux-amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ./bin/gocyclo https://github.com/adamdecaf/gocyclo/releases/download/2019-08-09/gocyclo-darwin-amd64; fi
  - chmod +x ./bin/gocyclo
  # apitest
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget -O ./bin/apitest https://github.com/moov-io/api/releases/download/v2019.11.01.1/apitest-linux-amd64; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget -O ./bin/apitest https://github.com/moov-io/api/releases/download/v2019.11.01.1/apitest-darwin-amd64; fi
  - chmod +x ./bin/apitest
  # - go get github.com/moov-io/api/cmd/apitest@master
before_script:
  - go get -u github.com/moov-io/go-client/client
  - GOFILES=$(find . -type f -name '*.go' | grep -v client | grep -v vendor)
  - go mod graph
script:
  # Just check gofmt on linux, it's the fastest builder
  - test -z $(gofmt -s -l $GOFILES)
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic
  - misspell -error -locale US $GOFILES
  - gocyclo -over 30 $GOFILES
  # Ignore a Consul CVE as we don't use that
  - go list -m all | ./bin/nancy -exclude-vulnerability CVE-2020-7219,fc041c7e-0c64-4b74-991e-64196a704ace
  - ./bin/golangci-lint run --timeout=1m --disable=errcheck
  - staticcheck ./cmd/server/*.go ./internal/*/*.go *.go
  - make dist
  - make test
deploy:
  provider: releases
  api_key:
    secure: qqO3w/v5vcYPUwN7Gk7yqhrXzjTIWKQ/t57UTCVO+gsIFjeJicjU1Vs2VT3nSAcZpxN/JfLeCbHzJAHwtJpvvHo/7ixesOmJSbv5+e7gGkVGpdIM5iCxbVVmzEcrNk/z41lM2cjhxMqZL7aFt1qL+9Zd/qYHE5bBWR0lRdyTf4Zz+KEj1DShx5B1eHv21xGHtd3tkk5MYNNCic2uTZ2NPsDxtrHp/er3OHzvqyqA03oFhkoPoG2+BsQr/HoFqZyydhUzWjXaVRWD+2Q/2Ao4VBtymuE6WwXj8LDbMZtl4Qs/g+jMHQODfPW78P+fbDbtOaOPYDVR2m10DNLqObX5C/pITVEPlyBBjrhe0iRpSYTo0Ik0io8FdGUsh0vVRHTwbn2e4GAZ2cg/BxsXYsh6UHtQJ0khjV3ZFOsgthTcVLBnEIH0SUKDa3Oku6tEQEqqhnpeutTLlv28Y7upXFdoa9pZ5suS4Uq+r6EWYAAS3tkSx5R0UCyTox+be0g2XK9/k3ZbkIMYg+wDF+A70mzCrZsji+VDDXWsY/dF6GrSWVekn9V/bXNWPi8Yt0aVqdikHluQEeEf63u6KTHV6aOLUT6kidbCi+ogqroe9UXj9gRVRK/73ChZyV+Q65bnSE6iCvhiHEkxEQP8wmVLsIiGx6+X0Fm5SyPEQ6tyBsGQk3c=
  file_glob: true
  file:
    - bin/apitest-*
  on:
    repo: moov-io/api
    tags: true
    go: 1.13.x
  skip_cleanup: true
after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make release-push
notifications:
  slack:
    secure: PSTsskD0WO58YXJLR8c3r1Ow2uDQ9LxCeDpwypdXPk/El3hZ/dg34gpWlclsKacUc+Qw9iAhBwWcoLV3MtPNT10gIu3Zam4u8y0zVSL/q32KD7jcQjoYG+7c6H6MpyoN2bD5mVCpyvT164ne4TLE1E9r3rsMfLiCWcRFM8PQTdIAFyBRZU1muSrk5VLPBTeXfQWo8Cy/Iko+5lEvXjnSJtxly2sXETmR9J7iGge7sxnh7pozLFk16lNC9d/ZAMWguDY9/tJ3mbag6LJIoJ44ThDx/pKihLE35m49SBVsk0C5PDcpHvLyLtb7fs2GsL6s4Km+eFCwO+nYMiUvhkIBIZPeagdkBgohHZYOaKcQ1jWUTYU1/xNem+Rr2RzfKLgMTmD8rV0O2L7rp7x6dVwiom+JgCKQfEqAK0G82ZXplixuFPeah4BW0TGCgfU8QdoQCiBurAbhJ7TLE+wBeiwRoKarc9AWG80KLmdQjE3t2WRT14PgqwTmgjaMeyDT45L5TkWJj50mKNFiDEYUl/NjOOgBDlL4dqaUZ5Oymj82cGQW6TIKzW8q+juHH1r3QRecWZNWYPVgyTjxdS6F5OD4FrwSsud6PLGpeh49W3cIkhiT4HsxIoVmgK5uuxEZoabnhhz3neV6FfqVAZ0nUshCkoVD/SXHlWGl1aYxAqtnlsY=
