openapi: 3.0.2
info:
  description: |
    _Note_: The Moov API and services are under development and could introduce breaking changes while reaching a stable status. We are looking for community feedback so please try out our code, [join the slack organization](https://slack.moov.io/) and give us some feedback! We announce releases on the [mailing list](https://groups.google.com/forum/#!forum/moov-users).

    The Moov API is organized around [REST](http://en.wikipedia.org/wiki/Representational_State_Transfer). Our API has predictable, resource-oriented URLs, and uses HTTP response codes to indicate API errors. We use built-in HTTP features, like HTTP authentication and HTTP verbs, which are understood by off-the-shelf HTTP clients. We support [cross-origin resource sharing](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing), allowing you to interact securely with our API from client-side web applications (never expose your secret API key in any public website's client-side code). [JSON](http://www.json.org/) is returned by all API responses, including errors, although you can generate client code via [OpenAPI code generation](https://github.com/OpenAPITools/openapi-generator) or the [OpenAPI editor](https://editor.swagger.io/) to convert responses to appropriate language-specific objects.

    The Moov API offers one method of authentication -- OAuth2 access tokens. The OAuth2 authentication is designed for automated access of our API. When an API requires a token generated using OAuth (2-legged), no end user is involved. You generate the token by passing your client credentials (Client ID and Client Secret) in a simple call to Create access token (`/oauth2/token`). The operation returns a token that is valid for a few hours and can be renewed; when it expires, you just repeat the call and get a new token. Making additional token requests will keep generating tokens. There are no hard or soft limits.

    The Moov API offers many services:
      - Automated Clearing House (ACH) origination and file management
      - Transfers management
      <!-- - Image Cash Ledger (ICL) file creation and modification API -->
      <!-- - Fed WIRE file creation and modification API -->

    The following order of API operations is suggested to start developing against the Moov API:

      1. [Create a Moov API user](#operation/...) with a unique email address
      1. Create a source Customer
         1. Approve
         1. Create an Account
            1. Verify or Approve
      1. Create a destination Customer
         1. Approve
         1. Create an Account
            1. Verify or Approve
      1. Initiate a Transfer

    ACH is implemented a RESTful API enabling ACH transactions to be submitted and received without a deep understanding of a full NACHA file specification. A `Customer` can initiate a `Transfer` as either a push (credit) or pull (debit) to another `Customer`. Customers must have a valid `Account` account for a `Transfer`.

    If you find a security related problem please contact us at [`security@moov.io`](mailto:security@moov.io).
  version: v1
  title: Moov API
  contact:
    email: security@moov.io
    url: https://moov.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: 'https://moov.io/images/logo.png'
    altText: Moov logo

servers:
  - url: http://localhost:9999
    description: Local development

tags:
  - name: Customers
    description: |
      Endpoints for searching, creating, and verifying individuals according to US government criteria for money movement within the country.
  - name: Organizations
    description: |
      Organization objects represent an group or large unit that initiates ACH transfers. These are typically businesses or business units who have configurations for their financial institution. The API allows you to create, delete, and update your organizations.
  - name: Tenants
    description: |
      Tenant objects represent a group of Organizations under one legal entity. Typically this is for a vendor who is reselling ACH services to many companies and assigns an Organization for each of their clients.
      Tenants are created with the admin HTTP server as part of user signup.
  - name: Transfers
    description: |
      Transfer objects create a transaction initiated by an originator to a receiver with a defined flow and fund amount. The API allows you to create or delete a transfers while the status of the transfer is pending.

paths:
# Customers
  /v1/customers:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers'
  /v1/customers/{customerID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D'
  /v1/customers/{customerID}/address:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1address'
  /v1/customers/{customerID}/metadata:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1metadata'
  /v1/customers/{customerID}/status:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1status'
  /v1/customers/{customerID}/accounts:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1accounts'
  /v1/customers/{customerID}/accounts/{accountID}/decrypt:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1accounts~1%7BaccountID%7D~1decrypt'
  /v1/customers/{customerID}/accounts/{accountID}/validate:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1accounts~1%7BaccountID%7D~1validate'
  /v1/customers/{customerID}/disclaimers:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1disclaimers'
  /v1/customers/{customerID}/documents:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1documents'
  /v1/customers/{customerID}/documents/{documentID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1documents~1%7BdocumentID%7D'
  /v1/customers/{customerID}/ofac:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1ofac'
  /v1/customers/{customerID}/refresh/ofac:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1refresh~1ofac'

# Tenants
  /v1/tenants:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1tenants"
  /v1/tenants/{tenantID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1tenants~1%7BtenantID%7D"

# Micro-Deposits
  /micro-deposits:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1micro-deposits"
  /micro-deposits/{microDepositID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1micro-deposits~1%7BmicroDepositID%7D"
  /accounts/{accountID}/micro-deposits:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1accounts~1%7BaccountID%7D~1micro-deposits"

# Organizations
  /v1/organizations:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1organizations"
  /v1/organizations/{organizationID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1organizations~1%7BorganizationID%7D"

# Transfers
  /v1/transfers:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1transfers"
  /v1/transfers/{transferID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1transfers~1%7BtransferID%7D"


components:
  schemas: {}
