openapi: 3.0.2
info:
  description: |
    The Moov API is an HTTP API served by Moov Financial, Inc for initiating money movements across the ACH payment rail. We follow [RESTful](http://en.wikipedia.org/wiki/Representational_State_Transfer) operations and naming conventions with predictable and standard HTTP status codes. We are available to help with onboarding or issues related to our services on [the Moov slack organization](https://slack.moov.io/) or via [support email](mailto:support@moov.io).

    ## Tenants and Organizations

    The Moov API offers two groups for organizating `Customer` records. A `Tenant` is the largest grouping which covers an entire business entity such as an LCC or corporation. Login credentials are tied to a Tenant and is extracted from the credentials provided on each request. An `Organization` is a grouping within a Tenant designed to represent a department (sales, marketing) and can be used for the entire LLC. On signup a Tenant is created with an Organization within through the web UI.

    <a href="https://raw.githubusercontent.com/moov-io/paygate/master/docs/images/tenant-in-paygate.png" target="_blank">
      <img src="https://raw.githubusercontent.com/moov-io/paygate/master/docs/images/tenant-in-paygate.png" />
    </a>

    ## Errors

    The API will respond with various standard HTTP status codes for errors which indicate how to resolve the request's problem. All errors will be in the `application/json` Content-Type with the below structure.

    ```
    {
      "error": "Descriptive message"
    }
    ```

    | Status Code | Summary           | Description                                                                                                       |
    |:-----------:|-------------------|-------------------------------------------------------------------------------------------------------------------|
    | 200         | OK                | The request was successful.                                                                                       |
    | 400         | Bad Request       | The request could not be understood by the server. The Incoming parameters might not be valid.                    |
    | 404         | Not Found         | The requested resource is not found or the credentials are not authorized to access it.                           |
    | 429         | Too Many Requests | Too many requests have been made in a short period of time. Please make requests at a slower rate or contact us.  |
    | 500         | Server Error      | The server could not return the representation due to an internal server error.                                   |
    | 501         | Not Implemented   | The requested operation is not supported (e.g. supports PUT but not POST etc.)                                    |

    ## Content-Type

    All requests and responses will be in the `application/json` MIME Content-Type unless otherwise specified.

    ## Cross-Origin Request Sharing

    We support [cross-origin resource sharing](http://en.wikipedia.org/wiki/Cross-origin_resource_sharing), allowing you to interact securely with our API from client-side web applications (never expose your secret API key in any public website's client-side code).

    ## Versioning

    The Moov API is currently using `/v1/` as the versioning prefix for all endpoints. This results in a base URI of `https://api.moov.io/v1/`.

    ## Clients

    Currently Moov offers a generated [Go client](https://github.com/moov-io/go-client) for usage with our API. The [OpenAPI specification](https://github.com/moov-io/api/blob/master/openapi.yaml) can be used to generate clients in other languages and we are open to supporting additonal languages. Please [contact us](mailto:support@moov.io) with feedback or suggestions.

    ## Authorization

    The Moov API offers one authorization method via a configured OIDC provider for your Tenant. This provider can be Google, Github, LDAP, or another vendor. We leverage OIDC becasue it allows immediate credential revocation, two-factor verification with that provider and a faster signup flow for users.

    ## Security

    Moov continiously monitors and scans our API services for security and privacy issues, but if you find a security related problem please contact us at [`security@moov.io`](mailto:security@moov.io).
  version: v1
  title: Moov API
  contact:
    email: security@moov.io
    url: https://moov.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  # termsOfService: http://example.com/terms/
  x-logo:
    url: 'https://moov.io/images/logo.png'
    altText: Moov logo

servers:
  - url: http://localhost:9999
    description: Local development

tags:
  - name: Customers
    description: |
      Endpoints for searching, creating, and verifying individuals according to US government criteria for money movement within the country.
  - name: Organizations
    description: |
      Organization objects represent an group or large unit that initiates ACH transfers. These are typically businesses or business units who have configurations for their financial institution. The API allows you to create, delete, and update your organizations.
  - name: Tenants
    description: |
      Tenant objects represent a group of Organizations under one legal entity. Typically this is for a vendor who is reselling ACH services to many companies and assigns an Organization for each of their clients.
      Tenants are created with the admin HTTP server as part of user signup.
  - name: Transfers
    description: |
      Transfer objects create a transaction initiated by an originator to a receiver with a defined flow and fund amount. The API allows you to create or delete a transfers while the status of the transfer is pending.

paths:
# Authentication
  /v1/authenticated:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1authenticated'
  /v1/identities:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1identities'
  /v1/identities/{identityID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1identities~1%7BidentityID%7D'
  /v1/identities/{identityID}/credentials:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1identities~1%7BidentityID%7D~1credentials'
  /v1/identities/{identityID}/credentials/{credentialID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1identities~1%7BidentityID%7D~1credentials~1%7BcredentialID%7D'
  /v1/invites:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1invites'
  /v1/invites/{inviteID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1invites~1%7BinviteID%7D'
  /v1/register:
    $ref: 'https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/paths/~1register'

# Customers
  /v1/customers:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers'
  /v1/customers/{customerID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D'
  /v1/customers/{customerID}/address:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1address'
  /v1/customers/{customerID}/metadata:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1metadata'
  /v1/customers/{customerID}/status:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1status'
  /v1/customers/{customerID}/accounts:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1accounts'
  /v1/customers/{customerID}/accounts/{accountID}/decrypt:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1accounts~1%7BaccountID%7D~1decrypt'
  /v1/customers/{customerID}/accounts/{accountID}/validate:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1accounts~1%7BaccountID%7D~1validate'
  /v1/customers/{customerID}/disclaimers:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1disclaimers'
  /v1/customers/{customerID}/documents:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1documents'
  /v1/customers/{customerID}/documents/{documentID}:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1documents~1%7BdocumentID%7D'
  /v1/customers/{customerID}/ofac:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1ofac'
  /v1/customers/{customerID}/refresh/ofac:
    $ref: 'https://raw.githubusercontent.com/moov-io/customers/master/openapi.yaml#/paths/~1customers~1%7BcustomerID%7D~1refresh~1ofac'

# Tenants
  /v1/tenants:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1tenants"
  /v1/tenants/{tenantID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1tenants~1%7BtenantID%7D"

# Organizations
  /v1/organizations:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1organizations"
  /v1/organizations/{organizationID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1organizations~1%7BorganizationID%7D"

# Transfers
  /v1/transfers:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1transfers"
  /v1/transfers/{transferID}:
    $ref: "https://raw.githubusercontent.com/moov-io/paygate/master/api/openapi.yaml#/paths/~1transfers~1%7BtransferID%7D"

components:
  schemas: {}
  securitySchemes:
    GatewayAuth:
      $ref: "https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/components/securitySchemes/GatewayAuth"
    LoginAuth:
      $ref: "https://raw.githubusercontent.com/moov-io/identity/master/api/openapi.yaml#/components/securitySchemes/LoginAuth"

security:
  - GatewayAuth: []
  - LoginAuth: []
